***SPAM-HAM Mail detection using Naive Bayes***

<h4 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h4>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('spam.csv')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df.shape

(5572, 2)

***Data Train-Test Split***

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Category,test_size=.2,random_state=1)

In [12]:
X_train.shape

(4457,)

In [14]:
X_test.shape

(1115,)

In [16]:
type(y_train)

pandas.core.series.Series

In [18]:
X_train.values

array(["Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?",
       'If you r @ home then come down within 5 min',
       "When're you guys getting back? G said you were thinking about not staying for mcr",
       ...,
       'CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C YA 2MORO! WHO NEEDS BLOKES',
       'Text & meet someone sexy today. U can find a date or even flirt its up to U. Join 4 just 10p. REPLY with NAME & AGE eg Sam 25. 18 -msg recd@thirtyeight pence',
       'K k:) sms chat with me.'], dtype=object)

In [20]:
type(X_train.values)

numpy.ndarray

***Create bag of words using CountVectorizer--> Creates bag for each unique words***

**Data Pre-Processing**

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [26]:
emails = [
            'Upto 20% discount reward!',
            'Hey mohan, discount Upto'
         ]

emails_cv = v.fit_transform(emails)
emails_cv

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [27]:
emails_cv.toarray()

array([[1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]], dtype=int64)

In [28]:
v.get_feature_names_out()

array(['20', 'discount', 'hey', 'mohan', 'reward', 'upto'], dtype=object)

In [29]:
pd.DataFrame(emails_cv.toarray(),columns=v.get_feature_names_out())

20  discount  hey  mohan  reward  upto
0   1         1    0      0       1     1
1   0         1    1      1       0     1

<h3>Data Preprocessing for Spam Dataset</h3>

In [31]:
v=CountVectorizer()
X_train_cv=v.fit_transform(X_train)

In [37]:
X_train_cv

<4457x7711 sparse matrix of type '<class 'numpy.int64'>'
	with 58978 stored elements in Compressed Sparse Row format>

In [38]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [39]:
X_train_cv.shape #total 7711 unique words 

(4457, 7711)

In [40]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      dtype=object)

In [41]:
df=pd.DataFrame(X_train_cv.toarray(),columns=v.get_feature_names_out())

In [46]:
df.iloc[[0]]

00  000  008704050406  0121  01223585236  01223585334  0125698789  02  \
0   0    0             0     0            0            0           0   0   

   0207  02072069400  ...  zed  zeros  zhong  zindgi  zoe  zoom  zouk  zyada  \
0     0            0  ...    0      0      0       0    0     0     0      0   

   èn  〨ud  
0   0    0  

[1 rows x 7711 columns]

In [50]:
pd.set_option('display.max_columns',None)

In [52]:
df

00  000  008704050406  0121  01223585236  01223585334  0125698789  02  \
0      0    0             0     0            0            0           0   0   
1      0    0             0     0            0            0           0   0   
2      0    0             0     0            0            0           0   0   
3      0    0             0     0            0            0           0   0   
4      0    0             0     0            0            0           0   0   
...   ..  ...           ...   ...          ...          ...         ...  ..   
4452   0    0             0     0            0            0           0   0   
4453   0    0             0     0            0            0           0   0   
4454   0    0             0     0            0            0           0   0   
4455   0    0             0     0            0            0           0   0   
4456   0    0             0     0            0            0           0   0   

      0207  02072069400  02073162414  02085076972  021  03  04  0430  05  \
0        0            0            0            0    0   0   0     0   0   
1        0            0            0            0    0   0   0     0   0   
2        0            0            0            0    0   0   0     0   0   
3        0            0            0            0    0   0   0     0   0   
4        0            0            0            0    0   0   0     0   0   
...    ...          ...          ...          ...  ...  ..  ..   ...  ..   
4452     0            0            0            0    0   0   0     0   0   
4453     0            0            0            0    0   0   0     0   0   
4454     0            0            0            0    0   0   0     0   0   
4455     0            0            0            0    0   0   0     0   0   
4456     0            0            0            0    0   0   0     0   0   

      050703  0578  06  07  07008009200  07090201529  07090298926  \
0          0     0   0   0            0            0            0   
1          0     0   0   0            0            0            0   
2          0     0   0   0            0            0            0   
3          0     0   0   0            0            0            0   
4          0     0   0   0            0            0            0   
...      ...   ...  ..  ..          ...          ...          ...   
4452       0     0   0   0            0            0            0   
4453       0     0   0   0            0            0            0   
4454       0     0   0   0            0            0            0   
4455       0     0   0   0            0            0            0   
4456       0     0   0   0            0            0            0   

      07123456789  07732584351  07734396839  07742676969  07753741225  \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               0            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
...           ...          ...          ...          ...          ...   
4452            0            0            0            0            0   
4453            0            0            0            0            0   
4454            0            0            0            0            0   
4455            0            0            0            0            0   
4456            0            0            0            0            0   

      0776xxxxxxx  07781482378  07786200117  078  07801543489  07808  \
0               0            0            0    0            0      0   
1               0            0            0    0            0      0   
2               0            0            0    0            0      0   
3               0            0            0    0            0      0   
4               0            0            0    0            0      0   
...   

In [54]:
v.vocabulary_

{'hi': 3423,
 'where': 7442,
 'are': 1051,
 'you': 7674,
 'we': 7370,
 're': 5564,
 'at': 1119,
 'and': 963,
 'they': 6794,
 'not': 4813,
 'keen': 3906,
 'to': 6889,
 'go': 3153,
 'out': 4985,
 'kind': 3940,
 'of': 4872,
 'am': 937,
 'but': 1578,
 'feel': 2795,
 'shouldn': 6077,
 'so': 6230,
 'can': 1632,
 'tomo': 6910,
 'don': 2408,
 'mind': 4474,
 'do': 2377,
 'if': 3593,
 'home': 3469,
 'then': 6782,
 'come': 1908,
 'down': 2433,
 'within': 7511,
 'min': 4471,
 'when': 7438,
 'guys': 3278,
 'getting': 3116,
 'back': 1196,
 'said': 5845,
 'were': 7419,
 'thinking': 6804,
 'about': 759,
 'staying': 6408,
 'for': 2927,
 'mcr': 4392,
 'tell': 6710,
 'my': 4650,
 'bad': 1199,
 'character': 1738,
 'which': 7448,
 'dnt': 2376,
 'lik': 4108,
 'in': 3633,
 'me': 4393,
 'll': 4156,
 'try': 7007,
 'change': 1730,
 'lt': 4243,
 'gt': 3254,
 'add': 813,
 'tat': 6671,
 'new': 4743,
 'year': 7650,
 'resolution': 5708,
 'waiting': 7308,
 'ur': 7147,
 'reply': 5688,
 'be': 1270,
 'frank': 2963,
 'go

***Train naive bayes model***

In [50]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [52]:
X_test

1078                         Yep, by the pretty sculpture
4028        Yes, princess. Are you going to make me moan?
958                            Welp apparently he retired
4642                                              Havent.
4674    I forgot 2 ask ü all smth.. There's a card on ...
                              ...                        
324     That would be great. We'll be at the Guild. Co...
1163    Free entry in 2 a wkly comp to win FA Cup fina...
86      For real when u getting on yo? I only need 2 m...
4214                     I attended but nothing is there.
90      Yeah do! Don‘t stand to close tho- you‘ll catc...
Name: Message, Length: 1115, dtype: object

**Evaluate Performance**

In [55]:
y_train

1642     ham
2899     ham
480      ham
3485     ham
157      ham
        ... 
905      ham
5192     ham
3980     ham
235     spam
5157     ham
Name: Category, Length: 4457, dtype: object

***Make X_test to bag of word--> test and tarin data should be same***

In [59]:
X_test_cv=v.transform(X_test)

In [63]:
X_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [67]:
X_test_cv.toarray().shape  #unique words 7711 cause here we did transform()--->means transform( )--> used previous bag of words

(1115, 7711)

**We did train test split first instade of encoding cause--> test data is totaly unknown sothat we just did bag of word for only train data**

In [70]:
model.score(X_test_cv,y_test)

0.989237668161435

In [74]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       968
        spam       0.98      0.94      0.96       147

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



**Test a data manually** 

In [77]:
emails = [
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Hey mohan, can we get together to watch footbal game tomorrow?'
]

In [79]:
email_cv=v.transform(emails)
email_cv.toarray().shape

(2, 7711)

In [81]:
model.predict(email_cv)

array(['spam', 'ham'], dtype='<U4')

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [84]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [86]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [88]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       968
        spam       0.98      0.94      0.96       147

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

